name: pr-validate

on:
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v4
    
      - uses: kcheriyath/csvlinter@V0.6.0
        with:
          fail_on_error: true
          
